export const watchesData = [
  {
    id: 1,
    name: "Classic Analog Watch",
    description: "A stylish analog watch perfect for everyday wear.",
    imageUrl: "/public/assets/watch1.png",
    affiliateLinks: {
      amazon: "https://www.amazon.com/your-amazon-affiliate-link-1",
      myntra: null,
      flipkart: "https://www.flipkart.com/your-flipkart-affiliate-link-3",
      ajio: null,
    },
    brand: "Generic",
  },
  {
    id: 2,
    name: "Digital Sport Watch",
    description: "A durable digital watch designed for sports and fitness.",
    imageUrl: "/public/assets/watch1.png",
    affiliateLinks: {
      amazon: null,
      myntra: "https://www.myntra.com/your-myntra-affiliate-link-2",
      flipkart: "https://www.flipkart.com/your-flipkart-affiliate-link-3",
      ajio: null,
    },
    brand: "Generic",
  },
  {
    id: 3,
    name: "Smart Watch Pro",
    description:
      "A feature-packed smartwatch with fitness tracking and notifications.",
    imageUrl: "/public/assets/watch1.png",
    affiliateLinks: {
      amazon: null,
      myntra: null,
      flipkart: "https://www.flipkart.com/your-flipkart-affiliate-link-3",
      ajio: null,
    },
    brand: "Generic",
  },
  {
    id: 4,
    name: "Casio Classic",
    description: "A classic and reliable watch from Casio.",
    imageUrl: "/public/assets/watch1.png",
    affiliateLinks: {
      amazon: "https://www.amazon.com/casio-affiliate-link-1",
      myntra: null,
      flipkart: null,
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 5,
    name: "Citizen Eco-Drive",
    description: "An eco-friendly watch powered by light.",
    imageUrl: "/public/assets/watch1.png",
    affiliateLinks: {
      amazon: "https://www.amazon.com/citizen-affiliate-link-2",
      myntra: null,
      flipkart: null,
      ajio: null,
    },
    brand: "Citizen",
  },
  {
    id: 6,
    name: "Timex Ironman",
    description: "A durable and sporty watch from Timex.",
    imageUrl: "/public/assets/watch1.png",
    affiliateLinks: {
      amazon: null,
      myntra: null,
      flipkart: "https://www.flipkart.com/timex-affiliate-link-3",
      ajio: null,
    },
    brand: "Timex",
  },
  {
    id: 7,
    name: "Casio Digital",
    description: "A basic but reliable Digital watch from casio",
    imageUrl: "/public/assets/watch1.png",
    affiliateLinks: {
      amazon: "https://www.amazon.com/casio-affiliate-link-1",
      myntra: null,
      flipkart: null,
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 8,
    name: "Citizen Elegant",
    description: "An elegant Watch from Citizen",
    imageUrl: "/public/assets/watch1.png",
    affiliateLinks: {
      amazon: "https://www.amazon.com/citizen-affiliate-link-2",
      myntra: null,
      flipkart: null,
      ajio: null,
    },
    brand: "Citizen",
  },
  {
    id: 9,
    name: "Timex Expedition",
    description: "A great watch from Timex",
    imageUrl: "/public/assets/watch1.png",
    affiliateLinks: {
      amazon: null,
      myntra: null,
      flipkart: "https://www.flipkart.com/timex-affiliate-link-3",
      ajio: null,
    },
    brand: "Timex",
  },
];
