export const watchesData = [
  {
    id: 1,
    name: "Casio Vintage Digital Grey Dial Unisex A-158Wa-1Q (D011)",
    description: "Casio Stainless Steel Men Vintage Digital Grey Dial Unisex A-158Wa-1Q (D011), Band Color-Silver.",
    imageUrl: "/assets/A-158Wa-1Q.jpg",
    affiliateLinks: {
      amazon: "https://amzn.to/42xZAb5",
      myntra: "https://myntr.it/YfuBBTJ",
      flipkart: "https://fktr.in/6q8M2eG",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 2,
    name: "CASIO Vintage A168WGG-1ADF",
    description: "CASIO Vintage A168WGG-1ADF Black Digital Dial Black Stainless Steel Band D181",
    imageUrl: "/assets/a168.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/3Zpn4Nb",
      myntra: "https://myntr.it/11l9588",
      flipkart: "https://fktr.in/2b4avKm",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 3,
    name: "Titan Karishma Zing Quartz",
    description: "Titan Karishma Zing Quartz Analog Blue Dial Leather Strap Watch for Men-1648SL01",
    imageUrl: "/assets/karishma.jpg",
    affiliateLinks: {
      amazon: "https://amzn.to/45LYSIN",
      myntra: "https://myntr.it/xMf4ZFP",
      flipkart: "",
      ajio: null,
    },
    brand: "Titan",
  },
  {
    id: 4,
    name: "HMT Galaxy S1G01",
    description: "HMT Galaxy S1G01 Roman Blue LS",
    imageUrl: "/assets/hmtRoman.jpg",
    affiliateLinks: {
      amazon: "https://hmtwatches.in/product_details?id=eyJpdiI6InRYT2FBVTU2dlljRUg1Y205VTkrblE9PSIsInZhbHVlIjoiNC9QMEt1eDE1dDlrQmNhTk1Na2hvQT09IiwibWFjIjoiZmMyM2VjNjc0MDYzNzA1MDJhMmNhMWQyYjMwM2M2NDlmODk2MGQwMjc0NWI1ZDM3MmJjNjZhYjk1NmE1NWNhMCIsInRhZyI6IiJ9",
      myntra: "https://myntr.it/xMf4ZFP",
      flipkart: "",
      ajio: null,
    },
    brand: "HMT",
  },
  {
    id: 5,
    name: "Casio Vintage A120WE-1ADF",
    description: "Casio Vintage A120WE-1ADF Black Digital Dial Silver Stainless Steel Band D321",
    imageUrl: "/assets/casio120we.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/4jJJ7Wh",
      myntra: "https://myntr.it/8cn13aQ",
      flipkart: "https://fktr.in/oSzNTTj",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 6,
    name: "Casio F-94Wa-9Dg(D053)",
    description: "Casio Resin Youth Series Digital Grey Dial Black Strap Unisex Watch - F-94Wa-9Dg(D053)",
    imageUrl: "/assets/casioF94WA.jpg",
    affiliateLinks: {
      amazon: "https://www.amazon.in/Casio-Vintage-Digital-Grey-Watch-F-94WA-9DG/dp/B002SG6ZBW",
      myntra: "https://myntr.it/W91z50W",
      flipkart: "https://fktr.in/KTXkpNy",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 7,
    name: "Casio Vintage DB-36-1AVDF",
    description: "Casio Vintage DB-36-1AVDF Digital Grey Dial Unisex Watch Black Resin Strap (DB23)",
    imageUrl: "/assets/casioDB361av.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/44fsUCD",
      myntra: "https://myntr.it/Z4c0oLF",
      flipkart: "https://fktr.in/QHJDb4a",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 8,
    name: "Casio MTP-1129A-7BRDF",
    description: "Casio Analog White Dial Men's Watch - MTP-1129A-7BRDF (A1709)",
    imageUrl: "/assets/casioMTP1129A.jpg",
    affiliateLinks: {
      amazon: "https://amzn.to/4jHx6kc",
      myntra: "",
      flipkart: "",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 9,
    name: "Casio Ws-1400H-1Avdf",
    description: "Casio Unisex Resin Digital Gray Dial Watch-Ws-1400H-1Avdf, Band Color-Black",
    imageUrl: "/assets/casioWS1400.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/4dZNZFC",
      myntra: "",
      flipkart: "https://fktr.in/Zya05yR",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 10,
    name: "Casio W-800H-5AVDF",
    description: "Casio Youth Digital Black Dial Unisex W-800H-5AVDF (D334)",
    imageUrl: "/assets/casioW800H.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/3ZppJ9D",
      myntra: "",
      flipkart: "https://fktr.in/Q4dwVsM",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 11,
    name: "Watch Band Spring Bar",
    description: "DIY Crafts 2 - Pcs Watch Band Spring Bar Remover Pin Linking Removal Tools Do It Your Self Tools",
    imageUrl: "/assets/springBar.jpg",
    affiliateLinks: {
      amazon: "https://amzn.to/3HvQvqQ",
      myntra: "",
      flipkart: "",
      ajio: null,
    },
    brand: "Tools",
  },
  {
    id: 12,
    name: "Casio PRJ-B001 Pro Trek",
    description: "Casio PRJ-B001 Pro Trek Wristwatch, Hiker Line Bluetooth Included, Tough Solar Biomass Plastic",
    imageUrl: "/assets/casioPRJb001.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/3HyPGxC",
      myntra: "",
      flipkart: "",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 13,
    name: "Casio G-Shock DW-5000R-1ADR",
    description: "Casio G-Shock DW-5000R-1ADR Digital Black Dial Men (G1660)",
    imageUrl: "/assets/casioDW500R.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/4kumI09",
      myntra: "https://myntr.it/CyMQ99t",
      flipkart: "",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 14,
    name: "Casio Vintage A158WEGV-9A",
    description: "Casio Vintage Gold & Green Digital Watch A158WEGB-9AWT",
    imageUrl: "/assets/casioA158WEGV.avif",
    affiliateLinks: {
      amazon: "",
      myntra: "",
      flipkart: "",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 15,
    name: "Casio X UNO A168WEUC-1A",
    description: "Casio X UNO A168WEUC-1A",
    imageUrl: "/assets/casioA168WEUC.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/446R6YH",
      myntra: "",
      flipkart: "",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 16,
    name: "Seiko 5 Sports Ash blue Limited Edition",
    description: "Seiko 5 Sports ‘Ash blue’ 1968 Recreation Limited Edition - SRPL03K1",
    imageUrl: "/assets/seikoAshblue.webp",
    affiliateLinks: {
      amazon: "",
      myntra: "",
      flipkart: "",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 17,
    name: "Casio G-Shock GA-2100-2A2DR",
    description: "Casio G-Shock GA-2100-2A2DR Blue Analog-Digital Dial Blue Resin Strap Men's Watch Shock and 200M Water Resistant G1521",
    imageUrl: "/assets/ga21002a2.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/4la7jCw",
      myntra: "https://myntr.it/x2dtayq",
      flipkart: "https://fktr.in/0q3YIj8",
      ajio: null,
    },
    brand: "Casio",
  },
   {
    id: 18,
    name: "Tissot PRX Powermatic 80 Chameleon Dial",
    description: "PRX Powermatic 80 Automatic Men chameleon Dial Analog Stainless Steel Watch T1374071105101",
    imageUrl: "/assets/ChameleonTissot.webp",
    affiliateLinks: {
      amazon: "",
      myntra: "https://myntr.it/KTK33k6",
      flipkart: "",
      ajio: null,
    },
    brand: "Tissot",
  },
   {
    id: 19,
    name: "Tissot PRX Powermatic 80 Ice Blue Dial",
    description: "PRX Powermatic 80 Automatic Men Ice blue Dial Analog Stainless Steel Watch T1374071135101",
    imageUrl: "/assets/iceBlueTissot.webp",
    affiliateLinks: {
      amazon: "",
      myntra: "https://myntr.it/NxhloZp",
      flipkart: "",
      ajio: null,
    },
    brand: "Tissot",
  },
  {
    id: 20,
    name: "Casio Enticer MTP-1381L-1AV",
    description: "Casio Enticer Analog Black Dial Men's Watch - MTP-1381L-1AVDF (A844)",
    imageUrl: "/assets/mtp1381L.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/40Ag1Sh",
      myntra: "",
      flipkart: "https://fktr.in/6hfAxpG",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 21,
    name: "Casio Enticer MTP-M300D-1AVDF",
    description: "Casio Men Stainless Steel Analog Black Dial Watch-Mtp-M300D-1Avdf, Band Color-Silver",
    imageUrl: "/assets/mtp300D1av.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/44sqO2h",
      myntra: "",
      flipkart: "https://fktr.in/2so4uf8",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 22,
    name: "Casio Enticer MTP-M105-1AV",
    description: "Casio Men Stainless Steel Analog Black Dial Watch-Mtp-M105D-1Avdf, Band Color-Silver",
    imageUrl: "/assets/mtpm1051av.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/44uvxQQ",
      myntra: "",
      flipkart: "https://fktr.in/3LthdPg",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 23,
    name: "Casio Enticer MTP-1302PD-1A1VEF",
    description: "Casio Enticer Men Analog Black Dial Men MTP-1302PD-1A1VEF (A2226)",
    imageUrl: "/assets/mtp13021a1v.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/3ZVa8Py",
      myntra: "https://myntr.it/6e35R5S",
      flipkart: "https://fktr.in/Ruv9rNV",
      ajio: null,
    },
    brand: "Casio",
  },
   {
    id: 24,
    name: "Tissot PRX Powermatic 80 Gold Dial",
    description: "Tissot PRX POWERMATIC 80 Men Gold Dial Automatic Stainless Steel Watch T1374073302100",
    imageUrl: "/assets/tissotprxgold.jpg",
    affiliateLinks: {
      amazon: "",
      myntra: "",
      flipkart: "",
      ajio: null,
    },
    brand: "Tissot",
  },
   {
    id: 25,
    name: "Casio Vintage AQ-230A-1DHDF",
    description: "CASIO Vintage AQ-230A-1DHDF Black Dial Silver Stainless Steel Band Analog-Digital Watch - For Men & Women AD01",
    imageUrl: "/assets/AQ-230A-1DMQ.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/44b0BX1",
      myntra: "https://myntr.it/rDnMuTp",
      flipkart: "https://fktr.in/VIKr4cT",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 26,
    name: "Casio G-Shock GMW-B5000D-1DR",
    description: "Casio G-Shock GMW-B5000D-1DR Bluetooth Digital Black Dial Men Watch Silver Metal Strap (G842)",
    imageUrl: "/assets/GMW-B5000D-1.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/3I82QSo",
      myntra: "https://myntr.it/EgJ663W",
      flipkart: "",
      ajio: null,
    },
    brand: "Casio",
  },
  {
    id: 27,
    name: "Casio Vintage B650WB-1BDF",
    description: "Casio Unisex-Adult Vintage B650WB-1BDF Black Digital Dial Black Stainless Steel Band D199",
    imageUrl: "/assets/B650WB-1B.avif",
    affiliateLinks: {
      amazon: "https://amzn.to/45WHVM5",
      myntra: "https://myntr.it/IvmnxpQ",
      flipkart: "https://fktr.in/XI05sFW",
      ajio: null,
    },
    brand: "Casio",
  },
];
